# Generated by Django 6.1.1 on 2026-09-08 14:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Виконавець')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Країна')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Назва альбому')),
                ('album_type', models.CharField(choices=[('lp', 'Повноформатний альбом (LP)'), ('ep', 'Міні-альбом (EP)'), ('single', 'Сінгл')], default='lp', max_length=10, verbose_name='Тип')),
                ('release_date', models.DateField(verbose_name='Дата релізу')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оцінка (1-5)')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music.artist', verbose_name='Виконавець')),
                ('genres', models.ManyToManyField(blank=True, related_name='albums', to='music.genre', verbose_name='Жанри')),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Назва треку')),
                ('duration_seconds', models.PositiveIntegerField(verbose_name='Тривалість (сек)')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.album', verbose_name='Альбом')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
